In [1]:
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
import joblib
import pickle as pkl
import random

In [2]:
dfsub=pd.read_csv('subreddit_info.csv')
dfusr=pd.read_csv('reddit_user_data_count.csv')

In [6]:
df=pd.merge(dfusr,dfsub,on='subreddit')
df

,user,subreddit,count,num_subscribers,over18,public_description
0,------Username------,AskReddit,20,32374022.0,False,r/AskReddit is the place to ask and answer tho...
1,----Michel----,AskReddit,6,32374022.0,False,r/AskReddit is the place to ask and answer tho...
2,----petrichor----,AskReddit,31,32374022.0,False,r/AskReddit is the place to ask and answer tho...
3,--Anarchaeopteryx--,AskReddit,1,32374022.0,False,r/AskReddit is the place to ask and answer tho...
4,--Orchid--,AskReddit,84,32374022.0,False,r/AskReddit is the place to ask and answer tho...
...,...,...,...,...,...,...
1646701,zynu,developer,1,10632.0,False,"The home for developers. Post your projects, g..."
1646702,zzreywasol,SubaruOldSchool,2,221.0,False,A place for older Subarus in all their glory. ...
1646703,zzzayah,DylanPierce,3,5.0,False,Dylan Pierce happy sad Brennan Smith scary man
1646704,zzzayah,Zynn,1,1955.0,False,Hello! This is a community all about Zynn! Ple...
1646705,zzzayah,actualeyebleach,1,17.0,False,Bleach being poured into eyes

In [7]:
dfcsub=df.groupby(by=['subreddit'])['count'].count().reset_index()
dfcsub

                  subreddit  count
0             00sAesthetics      1
1                 00sBabies      1
2              00snostalgia      3
3                  070Shake      1
4           08_e_09_Diversi      1
...                     ...    ...
57847            zxspectrum      3
57848                   zyn      2
57849             zyramains     10
57850                  zyzz     10
57851  zzzzzzzzzzzzzzzzzzzz      1

[57852 rows x 2 columns]

In [8]:
df.groupby(by=['subreddit'])['count'].count().reset_index()

                  subreddit  count
0             00sAesthetics      1
1                 00sBabies      1
2              00snostalgia      3
3                  070Shake      1
4           08_e_09_Diversi      1
...                     ...    ...
57847            zxspectrum      3
57848                   zyn      2
57849             zyramains     10
57850                  zyzz     10
57851  zzzzzzzzzzzzzzzzzzzz      1

[57852 rows x 2 columns]

In [9]:
df

,user,subreddit,count,num_subscribers,over18,public_description
0,------Username------,AskReddit,20,32374022.0,False,r/AskReddit is the place to ask and answer tho...
1,----Michel----,AskReddit,6,32374022.0,False,r/AskReddit is the place to ask and answer tho...
2,----petrichor----,AskReddit,31,32374022.0,False,r/AskReddit is the place to ask and answer tho...
3,--Anarchaeopteryx--,AskReddit,1,32374022.0,False,r/AskReddit is the place to ask and answer tho...
4,--Orchid--,AskReddit,84,32374022.0,False,r/AskReddit is the place to ask and answer tho...
...,...,...,...,...,...,...
1646701,zynu,developer,1,10632.0,False,"The home for developers. Post your projects, g..."
1646702,zzreywasol,SubaruOldSchool,2,221.0,False,A place for older Subarus in all their glory. ...
1646703,zzzayah,DylanPierce,3,5.0,False,Dylan Pierce happy sad Brennan Smith scary man
1646704,zzzayah,Zynn,1,1955.0,False,Hello! This is a community all about Zynn! Ple...
1646705,zzzayah,actualeyebleach,1,17.0,False,Bleach being poured into eyes

In [10]:
df.drop(columns=['count','num_subscribers','over18'],inplace=True,axis=1)

In [11]:
df.head()

,user,subreddit,public_description
0,------Username------,AskReddit,r/AskReddit is the place to ask and answer tho...
1,----Michel----,AskReddit,r/AskReddit is the place to ask and answer tho...
2,----petrichor----,AskReddit,r/AskReddit is the place to ask and answer tho...
3,--Anarchaeopteryx--,AskReddit,r/AskReddit is the place to ask and answer tho...
4,--Orchid--,AskReddit,r/AskReddit is the place to ask and answer tho...

In [12]:
dff=df.merge(dfcsub,on='subreddit')
dff.head()

,user,subreddit,public_description,count
0,------Username------,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
1,----Michel----,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
2,----petrichor----,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
3,--Anarchaeopteryx--,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
4,--Orchid--,AskReddit,r/AskReddit is the place to ask and answer tho...,21021

In [13]:
dff

,user,subreddit,public_description,count
0,------Username------,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
1,----Michel----,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
2,----petrichor----,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
3,--Anarchaeopteryx--,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
4,--Orchid--,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
...,...,...,...,...
1646701,zynu,developer,"The home for developers. Post your projects, g...",1
1646702,zzreywasol,SubaruOldSchool,A place for older Subarus in all their glory. ...,1
1646703,zzzayah,DylanPierce,Dylan Pierce happy sad Brennan Smith scary man,1
1646704,zzzayah,Zynn,Hello! This is a community all about Zynn! Ple...,1
1646705,zzzayah,actualeyebleach,Bleach being poured into eyes,1

In [16]:
gt=dff[dff['count']>10]

In [17]:
len(gt.subreddit.unique())

12790

In [18]:
gt

,user,subreddit,public_description,count
0,------Username------,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
1,----Michel----,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
2,----petrichor----,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
3,--Anarchaeopteryx--,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
4,--Orchid--,AskReddit,r/AskReddit is the place to ask and answer tho...,21021
...,...,...,...,...
1633423,studiodepan,StreetwearFits,A place to post your streetwear outfits.,14
1633424,sungkim92,StreetwearFits,A place to post your streetwear outfits.,14
1633425,swaggitravi,StreetwearFits,A place to post your streetwear outfits.,14
1633426,thedoc9963,StreetwearFits,A place to post your streetwear outfits.,14
1633427,theincrediblechris,StreetwearFits,A place to post your streetwear outfits.,14

In [19]:
ft=gt.pivot_table(index='subreddit',columns='user',values='count').fillna(0)
ft

user,------Username------,----Michel----,----The_Truth-----,----meh----,----petrichor----,--Aldo--,--Anarchaeopteryx--,--Jlakshan--,--Orchid--,--Superb,...,zxxx,zy1oh,zyht56,zylophon3kid,zynu,zyuhel,zyzzguido55,zzMarc,zzreywasol,zzzayah
subreddit,,,,,,,,,,,,,,,,,,,,,
0sanitymemes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1000lbsisters,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100gecs,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100thieves,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100yearsago,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zombies,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zoology,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zootopia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zuckmemes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zurich,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
msubfeat=csr_matrix(ft.values)

In [28]:
from sklearn.neighbors import NearestNeighbors
knn=NearestNeighbors(metric='cosine')

In [29]:
knn.fit(msubfeat)

NearestNeighbors(metric='cosine')

In [26]:
ft.to_csv('subredditfeats10.csv')

In [31]:
with open('knn10.pickle','wb') as fout:
    pkl.dump(knn,fout)